config/routes.rb
Rails.application.routes.draw do
  namespace :account do
    resources :registrations, only: %i[show new create]
  end
  namespace :accounts do
    resources :freezes, only: :index
  end
  resources :accounts, only: %i[index show new create] do
    resource :freeze, only: %i[create destroy], module: 'accounts'
  end
end

app/models/account.rb
class Account < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, length: { in: 8..30 },
                       format: { with: /\A[a-z0-9]+\z/i,
                                 message: 'は半角英数とハイフン（-）のみお使いください。' }
  has_one :freeze, dependent: :destroy
end

app/models/account/freeze.rb
class Account::Freeze < ApplicationRecord
  belongs_to :account
end

app/models/account/registration.rb
class Account::Registration < ApplicationRecord
  validates :email, presence: true
  validate :email_of_account_is_unique
  validates :terms_of_service, acceptance: true

  private
    def email_of_account_is_unique
      errors.add(:email, 'は既に使用されています。') if Account.find_by(email: email)
    end
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/account/registrations_controller.rb
class Account::RegistrationsController < ApplicationController
  before_action :set_account_registration, only: [:show, :edit, :update, :destroy]

  # GET /account/registrations
  def index
    @account_registrations = Account::Registration.all
  end

  # GET /account/registrations/1
  def show
  end

  # GET /account/registrations/new
  def new
    @account_registration = Account::Registration.new
  end

  # GET /account/registrations/1/edit
  def edit
  end

  # POST /account/registrations
  def create
    @account_registration = Account::Registration.new(account_registration_params)

    if @account_registration.save
      Account::RegistrationMailer.with(account_registration: @account_registration).confirm.deliver_later
      redirect_to @account_registration, notice: 'Registration was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /account/registrations/1
  def update
    if @account_registration.update(account_registration_params)
      redirect_to @account_registration, notice: 'Registration was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /account/registrations/1
  def destroy
    @account_registration.destroy
    redirect_to account_registrations_url, notice: 'Registration was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_registration
      @account_registration = Account::Registration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_registration_params
      params.require(:account_registration).permit(:email, :terms_of_service)
    end
end

app/controllers/accounts/freezes_controller.rb
class Accounts::FreezesController < ApplicationController
  def index
    @accounts = Account.joins(:freeze).where.not(freeze: nil).order(:id)
  end

  def create
    Account.find(params[:account_id]).create_freeze
    redirect_to accounts_url
  end

  def destroy
    Account::Freeze.where(account_id: params[:account_id]).destroy_all
    redirect_to accounts_url
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :set_expiring_sid_and_account_registration, only: %i[new create]

  # GET /accounts
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
    @account.email = @account_registration.email
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  def create
    @account = Account.new(account_params)
    @account.email = @account_registration.email

    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /accounts/1
  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    redirect_to accounts_url, notice: 'Account was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def set_expiring_sid_and_account_registration
      @expiring_sid = params[:expiring_sid] || params[:account][:expiring_sid]
      @account_registration = Account::Registration.find_signed(@expiring_sid, purpose: :registration)
      head :unprocessable_entity if @account_registration.nil?
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/account/registrations_helper.rb
module Account::RegistrationsHelper
end

app/helpers/accounts/freezes_helper.rb
module Accounts::FreezesHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Email:</strong>
    <%= @account.email %>
  </p>
  <%= form.hidden_field :expiring_sid, value: @expiring_sid %>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/freezes/index.html.erb
<h1>Freezed Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.email %></td>
        <td><%= link_to 'Show', account %></td>
        <td>
          <%= button_to 'To Unfreeze', account_freeze_path(account), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.email %></td>
        <td><%= link_to 'Show', account %></td>
        <td>
          <% if account.freeze %>
            <%= button_to 'To Unfreeze', account_freeze_path(account), method: :delete %>
          <% else %>
            <%= button_to 'To Freeze', account_freeze_path(account) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TryAccount</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>